### ISSUE TITLE
errorCode==90005,errorMsg==合成失败：Expected HTTP 101 response but was '200 OK',traceId==null

### ISSUE THREAD

**Issue by muyexiaogui** [data-baker/BakerSynthesizer#1]
################################################################################################
2020-07-07 10:38:01.334 21235-21365/com.baker.synthesizer W/System.err: java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'
2020-07-07 10:38:01.335 21235-21365/com.baker.synthesizer W/System.err:     at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
2020-07-07 10:38:01.335 21235-21365/com.baker.synthesizer W/System.err:     at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
2020-07-07 10:38:01.335 21235-21365/com.baker.synthesizer W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
2020-07-07 10:38:01.335 21235-21365/com.baker.synthesizer W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2020-07-07 10:38:01.335 21235-21365/com.baker.synthesizer W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-07-07 10:38:01.335 21235-21365/com.baker.synthesizer W/System.err:     at java.lang.Thread.run(Thread.java:784)

################################################################################################
您好 使用你家SDK进行私有云部署的时候，程序运行总是报这个错误，请问一下可能是因为什么而导致这个错误？

**Comment by data-baker** [comment]
> java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'

您好，请确定服务器地址是否正确，是wss://xxx格式的吗？从错误日志来看是属于与服务器握手成功，返回101 code提示升级成websocket协议。

**Comment by muyexiaogui** [comment]
> > java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'
> 
> 您好，请确定服务器地址是否正确，是wss://xxx格式的吗？从错误日志来看是属于与服务器握手成功，返回101 code提示升级成websocket协议。

好的  我用的http://xxx.xxx.xx.x:xxx/tts?audiotype=6&rate=1&access_token=default&&domain=1&language=zh&voice_name=jingjing做的请求，我修改为ws试试，谢谢
